name: Build ProjectNERV (Self-hosted)

on:
  workflow_dispatch:
  push:
    branches:
      - 'paradigm'

jobs:
  build:
    runs-on: self-hosted


    steps:
      - name: Clean repo workspace
        run: |
          echo "Cleaning $GITHUB_WORKSPACE..."
          rm -rf "$GITHUB_WORKSPACE"
          mkdir -p "$GITHUB_WORKSPACE"

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare Odin directory
        run: |
          mkdir -p out/
          ln -s ~/odin out/odin || true

      - name: Set up build environment
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            p7zip-full jq attr ccache clang ffmpeg golang \
            libbrotli-dev libgtest-dev libprotobuf-dev libunwind-dev libpcre2-dev \
            libzstd-dev lld jq protobuf-compiler pcre2-utils webp cmake\
            curl xxd patchelf flex bison libarchive-tools build-essential python3.13-venv device-tree-compiler openjdk-21-jdk
          sudo modprobe erofs f2fs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo -n "${{ secrets.PLATFORM_KEY_PK8 }}" | base64 --decode > security/platform.pk8
          echo -n "${{ secrets.PLATFORM_KEY_PEM }}" | base64 --decode > security/platform.x509.pem

      - name: Build all targets
        run: |
          TARGETS="gts7xlwifi gts7lwifi gts7xl gts7l"
          for target in $TARGETS; do
            echo "==== Building for $target ===="
            source ./buildenv.sh $target
            ./scripts/build_dependencies.sh
            ./scripts/download_fw.sh --ignore-target
            ./scripts/extract_fw.sh --ignore-target
            ./scripts/download_fw.sh --ignore-source
            ./scripts/extract_fw.sh --ignore-source

            if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
              ./scripts/make_rom.sh
            else
              ./scripts/make_rom.sh --no-rom-zip
            fi
            DEST=~/onedrive/ROMS/$target
            mkdir -p "$DEST"
            find out -maxdepth 1 -type f -name "*.zip" -exec cp {} "$DEST/" \;
          done

      - name: Upload to GoFile
        if: github.event_name == 'workflow_dispatch'
        run: |
          ZIP_FILE=$(find out -maxdepth 1 -type f -name "*.zip" | head -n 1)
          RESPONSE=$(curl -s -F "file=@$ZIP_FILE" -F "token=${{ secrets.GOFILE_TOKEN }}" -F "folderId=${{ secrets.GOFILE_FOLDER_ID }}" "https://upload-eu-par.gofile.io/uploadFile")
          echo "Download link:"
          echo "$RESPONSE" | jq -r '.data.downloadPage'
